//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seattle.DoIT.PoliceReports.Web.UserProfileServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://www.seattle.gov/DoIT/SPD/Services/2010/05/")]
    [System.SerializableAttribute()]
    internal partial class UserProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.seattle.gov/DoIT/SPD/Services/2010/05/", ConfigurationName="UserProfileServices.UserProfileService")]
    internal interface UserProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.seattle.gov/DoIT/SPD/Services/2010/05/UserProfileService/GetByUserName" +
            "", ReplyAction="http://www.seattle.gov/DoIT/SPD/Services/2010/05/UserProfileService/GetByUserName" +
            "Response")]
        Seattle.DoIT.PoliceReports.Web.UserProfileServices.UserProfile GetByUserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.seattle.gov/DoIT/SPD/Services/2010/05/UserProfileService/Add", ReplyAction="http://www.seattle.gov/DoIT/SPD/Services/2010/05/UserProfileService/AddResponse")]
        void Add(Seattle.DoIT.PoliceReports.Web.UserProfileServices.UserProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.seattle.gov/DoIT/SPD/Services/2010/05/UserProfileService/Update", ReplyAction="http://www.seattle.gov/DoIT/SPD/Services/2010/05/UserProfileService/UpdateRespons" +
            "e")]
        void Update(Seattle.DoIT.PoliceReports.Web.UserProfileServices.UserProfile userProfile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface UserProfileServiceChannel : Seattle.DoIT.PoliceReports.Web.UserProfileServices.UserProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class UserProfileServiceClient : System.ServiceModel.ClientBase<Seattle.DoIT.PoliceReports.Web.UserProfileServices.UserProfileService>, Seattle.DoIT.PoliceReports.Web.UserProfileServices.UserProfileService {
        
        public UserProfileServiceClient() {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Seattle.DoIT.PoliceReports.Web.UserProfileServices.UserProfile GetByUserName(string userName) {
            return base.Channel.GetByUserName(userName);
        }
        
        public void Add(Seattle.DoIT.PoliceReports.Web.UserProfileServices.UserProfile userProfile) {
            base.Channel.Add(userProfile);
        }
        
        public void Update(Seattle.DoIT.PoliceReports.Web.UserProfileServices.UserProfile userProfile) {
            base.Channel.Update(userProfile);
        }
    }
}
