//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seattle.DoIT.PoliceReports.Web.SsoServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicProfile", Namespace="http://www.seattle.gov/DoIT/SSO/2009/06/")]
    [System.SerializableAttribute()]
    internal partial class BasicProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsEnabled {
            get {
                return this.IsEnabledField;
            }
            set {
                if ((this.IsEnabledField.Equals(value) != true)) {
                    this.IsEnabledField = value;
                    this.RaisePropertyChanged("IsEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.seattle.gov/DoIT/SSO/2009/06/", ConfigurationName="SsoServices.BasicProfileService")]
    internal interface BasicProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.seattle.gov/DoIT/SSO/2009/06/BasicProfileService/GetByUserName", ReplyAction="http://www.seattle.gov/DoIT/SSO/2009/06/BasicProfileService/GetByUserNameResponse" +
            "")]
        Seattle.DoIT.PoliceReports.Web.SsoServices.BasicProfile GetByUserName(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.seattle.gov/DoIT/SSO/2009/06/BasicProfileService/GetByEmail", ReplyAction="http://www.seattle.gov/DoIT/SSO/2009/06/BasicProfileService/GetByEmailResponse")]
        Seattle.DoIT.PoliceReports.Web.SsoServices.BasicProfile GetByEmail(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface BasicProfileServiceChannel : Seattle.DoIT.PoliceReports.Web.SsoServices.BasicProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class BasicProfileServiceClient : System.ServiceModel.ClientBase<Seattle.DoIT.PoliceReports.Web.SsoServices.BasicProfileService>, Seattle.DoIT.PoliceReports.Web.SsoServices.BasicProfileService {
        
        public BasicProfileServiceClient() {
        }
        
        public BasicProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Seattle.DoIT.PoliceReports.Web.SsoServices.BasicProfile GetByUserName(string username) {
            return base.Channel.GetByUserName(username);
        }
        
        public Seattle.DoIT.PoliceReports.Web.SsoServices.BasicProfile GetByEmail(string email) {
            return base.Channel.GetByEmail(email);
        }
    }
}
