<table width="775" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#5b5bb1">
<tr>
  <td align="center" colspan="2" style="background:#fff;font-size:10px;padding:5px"><b>Site disclaimer:</b> The Seattle Police Department's website was developed to provide general information.<br>Data contained at this location is generally not reviewed for legal sufficiency. <a style="font-size:10px;padding:5px" href="/police/disclaimer.htm">More info...</a></td>
</tr>		
<tr>
  <td bgcolor="#b5d1f1" width="55"><a href="/police/about/calea.htm"><img src="/police/Images/CELEA_footer.gif" alt="CALEA Accredited Organization" border="0" height="60" width="55"></a></td>
  <td align="center" bgcolor="#b5d1f1" width="720"><a href="/police/">Home</a> | <a href="/police/accountability/">Accountability / OPA</a> | <a href="/police/precincts">Precincts</a> | <a href="/police/crime/">Crime Info</a> | <a href="/police/prevention/">Safety &amp; Prevention</a><br>
  <a href="/police/programs/">Programs &amp; Services </a> | <a href="/police/jobs/">Police Jobs </a> | <a href="/police/involved/">Get Involved</a> | <a href="/police/about/">About Us</a> | <a href="/police/contact/">Contact Us</a><br>
  <div align="left" style="padding:3px;padding-top:12px"><i style="font-size:10px;">The Seattle Police Department is a <a href="/police/about/calea.htm">CALEA Accredited Agency</a>.</i></div>
</td>
</tr>
</table>