<noindex><!--begin TransHead-->
<table width="775" cellpadding="0" cellspacing="0" border="0">
<tr>
  <td width="487"><a href="/police/"><img src="/police/images/policeHeaderDept.gif" alt="Link to Seattle Police Department Home Page" width="487" height="28" border="0"></a></td>
  <td width="96"><a href="/police/"><img src="/police/images/policeHeaderHome.gif" alt="Link to Seattle Police Department Home Page" width="96" height="28" border="0"></a></td>
  <td width="86"><a href="/police/about/"><img src="/police/images/policeHeaderAbout.gif" alt="Link to Seattle Police Department About Us Page" width="86" height="28" border="0"></a></td>
  <td width="106"><a href="/police/contact/"><img src="/police/images/policeHeaderContact.gif" alt="Link to Seattle Police Department Contact Us Page" width="106" height="28" border="0"></a></td>
</tr>
<tr>
  <td width="487"><img src="/police/images/policeHeaderTagline.gif" alt="Preventing Crime, enforcing, laws, supporting public safety" width="487" height="28" border="0"></td>
  <td width="288" colspan="3"><img src="/police/images/policeHeaderDirector.gif" alt="Interim Chief John Diaz" width="288" height="28" border="0"></td>
</tr>
</table>
<div align="center">
<table background="/police/images/Icons/navGold.gif" width="775" border="0" cellspacing="0" cellpadding="1" bordercolor="#666666" bgcolor="#FFFFFF" style="border: thin solid #A2A2D9;">
<tr>

<td nowrap align="center"><p><a href="/police/accountability/" style="font-family: Verdana; font-size: 9pt; color: #5B5BB1; font-weight: bold; line-height:1.7;text-decoration: none;">Accountability/OPA</a></p></td>
<td nowrap align="center" style="border-left-color: #A2A2D9; border-left-style: dotted; border-left-width: thin;"><p><a href="/police/precincts"  style="font-family: Verdana; font-size: 9pt; color: #5B5BB1; font-weight: bold;text-decoration: none;">Precincts</a></p></td>
<td nowrap align="center" style="border-left-color: #A2A2D9; border-left-style: dotted; border-left-width: thin;"><p><a href="/police/crime/"  style="font-family: Verdana; font-size: 9pt; color: #5B5BB1; font-weight: bold;text-decoration: none;">Crime Info</a></p></td>
<td nowrap align="center" style="border-left-color: #A2A2D9; border-left-style: dotted; border-left-width: thin;"><p><a href="/police/prevention/" style="font-family: Verdana; font-size: 9pt; color: #5B5BB1; font-weight: bold;text-decoration: none;">Safety &amp; Prevention</a></p></td>
<td nowrap align="center" style="border-left-color: #A2A2D9; border-left-style: dotted; border-left-width: thin;"><p><a href="/police/programs/" style="font-family: Verdana; font-size: 9pt; color: #5B5BB1; font-weight: bold;text-decoration: none;">Programs &amp; Services</a></p></td>
<td nowrap align="center" style="border-left-color: #A2A2D9; border-left-style: dotted; border-left-width: thin;" id="policeJobs"><p><a href="/police/jobs/" style="font-family: Verdana; font-size: 9pt; color: #5B5BB1; font-weight: bold;text-decoration: none;">Jobs</a></p></td>
<td nowrap align="center" style="border-left-color: #A2A2D9; border-left-style: dotted; border-left-width: thin;" id="getInvolved"><p><a href="/police/involved/" style="font-family: Verdana; font-size: 9pt; color: #5B5BB1; font-weight: bold;text-decoration: none;">Get Involved</a></p></td>
</tr>
</table>
</div>


<!--end TransHead--></noindex>
<SCRIPT language="JavaScript">
whichDept = "Police"
whichStyle = "police_frontend"
</SCRIPT>