<noindex>
<script type="text/javascript" language="javascript" src="/js/ypSlideOutMenusA.js"></script>
<style type="text/css">
<!--
.menuCont .options {
		border-left:1px solid #333333;				
		background-color:#E9E9E9;
	}
.menu a, .menu a:link, .menu a:visited {
		color:#666666;
		display:block;		
		padding-left:2px;
		padding-top:2px;
		padding-bottom:2px;
		border-bottom:1px solid #333333;
		font-family: arial, verdana;
		font-size: 11px;
		text-decoration:none;
		font-weight: bold;
		layer-background-color:#203945;
	}
.menu a:hover {
		background-color:#ADCFEB;
		layer-background-color:#99CCFF;
		color:#000000;
	}
//-->
</style>
<script type="text/javascript" language="javascript">
<!--
IE = document.all?1:0;
NAV6 = document.getElementById?1:0;

if(IE || NAV6){writeDept()}
function writeCSS(){
if(IE || NAV6){
document.write('<td width="86" height="23" style="position:relative;" align="center" id="DeptName" background="/2004_IMG/top_button.gif" onmouseover="ypSlideOutMenu.showMenu(\'dept\');this.style.backgroundImage=\'url(/2004_IMG/top_button_on.gif)\'" onmouseout="ypSlideOutMenu.hideMenu(\'dept\');this.style.backgroundImage=\'url(/2004_IMG/top_button.gif)\'"><a style="color:#666666;font-family:Arial;font-size:9pt;font-weight:bold;text-decoration:none;" href="/html/citizen/departments.htm">Departments</a></td>');
} else {
document.write('<td align="center" id="DeptName" background="/2004_IMG/top_button.gif"><a style="color:#666666;font-family:Arial;font-size:9pt;font-weight:bold;text-decoration:none;" href="/html/citizen/departments.htm">Departments</a></td>');
}
}
function testBrowser(){
  if(document.all){
  document.write('<input onclick="this.value=\'\'" style="font-size:9px;width:125px" value="Seattle.Gov" name="sp_q">&nbsp;<input style="font-size:9px" type="submit" value="Go">')
  }else{
  document.write('<input style="font-size:9px;" size="15" name="sp_q">&nbsp;<input style="font-size:9px;" type="submit" value="Go">')
  }
}

function writeCSS_NEW(){
if(IE || NAV6){
document.write('<td width="78" style="position:relative;" id="DeptName" onmouseover="ypSlideOutMenu.showMenu(\'dept\');" onmouseout="ypSlideOutMenu.hideMenu(\'dept\');"><a href="/html/citizen/departments.htm"><img src="/2004_img/btn_dept.gif" alt="City Departments" width="78" height="23" border="0"></a></td>');
} else {
document.write('<td width="78"><img src="/2004_img/btn_dept.gif" alt="City Departments" width="78" height="23" border="0"></td>');
}
}
function video(id){
loC = "http://www.seattlechannel.org/videos/video.asp?ID="+id
//alert (loC)
window.open(loC,"viewer","location=no,status=yes,scrollbars=no,resizable=yes,width=800,height=580")
}

function videoContent(id){
loC = "http://www.seattlechannel.org/videos/video.asp?ID="+id+"&content=1"
window.open(loC,"viewer","location=no,status=yes,scrollbars=no,resizable=yes,width=800,height=580")
}
//-->
</script>

<table width="775" cellpadding="0" cellspacing="0" border="0">
<tr>
  <td width="81"><a href="http://www.seattle.gov/"><img src="/2004_img/btn_home.gif" alt="Seattle.gov Home Page" width="81" height="23" border="0" /></a></td>
  <td width="81"><a href="http://www.seattle.gov/html/citizen/services.htm"><img src="/2004_img/btn_services.gif" alt="City Services" width="81" height="23" border="0" /></a></td>
  <script type="text/javascript" language="javascript">writeCSS_NEW()</script>

  <td width="86"><a href="http://www.seattle.gov/directory/"><img src="/2004_img/btn_staff.gif" alt="Staff Directory" width="86" height="23" border="0" /></a></td>
  <td width="86"><img src="/2004_img/bar_grey2.gif" alt="[WEB GRAPHIC]" width="222" height="23" border="0" /></td>  
  <td width="83"><a href="/html/pan.htm"><img src="/2004_img/btn_aboutgov.gif" alt="About Seattle.gov" width="98" height="23" border="0" /></a></td>
  <td width="75"><a href="/html/feedback.htm"><img src="/2004_img/btn_contacts.gif" alt="City Contacts" width="75" height="23" border="0" /></a></td>
  <td width="54"><a href="/html/sitemap.htm"><img src="/2004_img/btn_sitemap.gif" alt="Site Map" width="54" height="23" border="0" /></a></td>
</tr>  
</table>
<table width="775" cellpadding="0" cellspacing="0" border="0">
<tr>
  <td width="540"><a href="http://www.seattle.gov"><img src="/2004_img/seattle_header.jpg" alt="Seattle.gov Home Page" width="540" height="59" border="0" /></a></td>
  <td width="235" bgcolor="#EDF7FF" style="background-image:url(/2004_IMG/search_bkg.gif);color:#666666;font-family:Arial;font-size:9pt;font-weight:bold;text-decoration:none;">

  <form style="MARGIN:0px;PADDING:-10px;" method="get" action="http://find.seattle.gov/search">
  &nbsp;SEARCH:&nbsp;<input type="text" style="font-size:9px;width:125px;background-color:#FFFFFF;" name="q" size="18" maxlength="255" value="" />
  <input type="submit" name="btnG" value="Go" style="font-size:9px;width:25px"/>
  <input type="hidden" name="site" value="default_collection"/>
  <input type="hidden" name="client" value="cos_frontend"/>
  <input type="hidden" name="proxystylesheet" value="cos_frontend"/>
  <input type="hidden" name="output" value="xml_no_dtd"/>
  </form>

  </td>
</tr>
</table>
<table width="775" cellpadding="0" cellspacing="0" border="0">
<tr>
  <td colspan="9" style="background-color:#737373" id="colorBar"><img src="/2004_img/pixel.gif" alt="web graphic" width="3" height="3" border="0" /></td>
</tr>  
<tr>
  <td><a href="/html/business/default.htm"><img alt="Business" name="business" id="business" src="/2004_img/business_off.gif" onmouseover="ImgOn('business')" onmouseout="ImgOff('business')" width="84" height="24" border="0" /></a></td>
  <td><a href="/html/citizen/community.htm"><img alt="Community" name="community" id="community" src="/2004_img/community_off.gif" onmouseover="ImgOn('community')" onmouseout="ImgOff('community')" width="86" height="24" border="0" /></a></td>
  <td><a href="/html/VISITOR/culture.htm"><img alt="Arts and Recreation" name="culture" id="culture" src="/2004_img/culture_off.gif" onmouseover="ImgOn('culture')" onmouseout="ImgOff('culture')" width="86" height="24" border="0" /></a></td>
  <td><a href="/html/CITIZEN/climate.htm"><img alt="Climate" name="climate" id="climate" src="/2004_img/climate_off.gif" onmouseover="ImgOn('climate')" onmouseout="ImgOff('climate')" width="86" height="24" border="0" /></a></td>

  <td><a href="/html/CITIZEN/your.htm"><img alt="Government" name="government" id="government" src="/2004_img/government_off.gif" onmouseover="ImgOn('government')" onmouseout="ImgOff('government')" width="86" height="24" border="0" /></a></td>
  <td><a href="/html/CITIZEN/publicsafety.htm"><img alt="Public Safety" name="publicsafety" id="publicsafety" src="/2004_img/publicsafety_off.gif" onmouseover="ImgOn('publicsafety')" onmouseout="ImgOff('publicsafety')" width="86" height="24" border="0" /></a></td>
  <td><a href="/html/CITIZEN/getting.htm"><img alt="Transportation" name="transportation" id="transportation" src="/2004_img/transportation_off.gif" onmouseover="ImgOn('transportation')" onmouseout="ImgOff('transportation')" width="86" height="24" border="0" /></a></td>
  <td><a href="/html/CITIZEN/utility.htm"><img alt="Utilities" name="utilities" id="utilities" src="/2004_img/utilities_off.gif" onmouseover="ImgOn('utilities')" onmouseout="ImgOff('utilities')" width="86" height="24" border="0" /></a></td>
  <td><a href="/html/visitor/"><img alt="Visiting Seattle" name="visiting" id="visiting" src="/2004_img/visiting_off.gif" onmouseover="ImgOn('visiting')" onmouseout="ImgOff('visiting')" width="89" height="24" border="0" /></a></td>
</tr>
</table>
<script type="text/javascript" language="javascript"> 
var _menus = [	
	new ypSlideOutMenu("dept", "down", rePosx(), rePosy(), 190, 200, null)
	]
	document.write('<style type="text/css">' + ypSlideOutMenu.styleMod + '</style>');
	
	for (var i = 0; i < _menus.length; i++) {
		_menus[i].onactivate = new Function("document.getElementById('act" + i + "').className='active';");
		_menus[i].ondeactivate = new Function("document.getElementById('act" + i + "').className='';");
	}
</script>
</noindex>
